JFLAGS = -g
JC = javac

CLASSES = \
		simulation/Human.java \
		simulation/Country.java \
		test/Test.java

default: 
	$(JC) $(JFLAGS) $(CLASSES)

clean:
	$(RM) simulation/*.class
	$(RM) test/*.class

